### ISSUE TITLE
Create a class chooser

### ISSUE THREAD

**Issue by nahnsu** [nahnsu/DnDiscord#1]
If the intent is to create a new character, first direct the bot through a flow that chooses the class of the character based on a custom prompt, the chat history, and the newest message.

**Comment by nahnsu** [comment]
# Tasks
- [ ] Write prompt for class chooser
- [ ] After intent is to create, direct to class chooser
- [ ] Class chooser returns result to calling function
- [ ] Test that works

**Comment by nahnsu** [comment]
# Resources
- [5e API](https://open5e.com/)
